[package]
name = "furui"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya = { version = "0.10.7", features = ["async_tokio"] }
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log = { git = "https://github.com/aya-rs/aya-log", branch = "main" }
furui-common = { path = "../furui-common", features = ["user"] }
anyhow = "1.0.42"

log = "0.4"
simplelog = "0.11"
structopt = { version = "0.3" }
tokio = { version = "1.5.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "sync"] }

bytes = "1.1.0"
chrono = "0.4.19"

[[bin]]
name = "furui"
path = "src/main.rs"
