[package]
name = "furui"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya = { version = "0.10.7", features = ["async_tokio"] }
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log = { git = "https://github.com/aya-rs/aya-log", branch = "main" }
furui-common = { path = "../furui-common", features = ["user"] }
anyhow = "1.0"

log = "0.4"
simplelog = "0.11"
structopt = { version = "0.3" }
tokio = { version = "1.5", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "sync"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
libc = "0.2"
bytes = "1.1"
chrono = "0.4"
dns-lookup = "1.0.8"
bollard = "0.12.0"

[[bin]]
name = "furui"
path = "src/main.rs"
