name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    env:
      CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.arch }}

      - name: Add cargo binary path
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install bpf-linker
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: bpf-linker

      - name: Generate vmlinux.rs
        run: |
          cargo install aya-tool --git https://github.com/aya-rs/aya.git
          cargo install bindgen-cli

          aya-tool generate task_struct sockaddr_in sockaddr_in6 inet_sock ipv6hdr tcphdr udphdr icmphdr icmp6hdr > furui-ebpf/src/vmlinux.rs

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.arch }}-unknown-linux-musl

      - uses: actions/upload-artifact@v3
        with:
          name: furui-${{ matrix.arch }}
          path: target/${{ matrix.arch }}-unknown-linux-musl/release/furui
